sonar scan added

diff --git a/.github/workflows/buildanddeploy.yml b/.github/workflows/buildanddeploy.yml
--- a/.github/workflows/buildanddeploy.yml
+++ b/.github/workflows/buildanddeploy.yml
@@ -34,6 +34,24 @@ jobs:
       with:
         name: app-jar
         path: target/*.jar
+
+    - name: SonarCloud Scan
+      uses: SonarSource/sonarcloud-github-action@master
+      with:
+        args: >
+          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
+          -Dsonar.organization=${{ secrets.SONAR_ORG }}
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+    - name: Quality Gate
+      run: |
+        quality_gate_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
+        if [ "$quality_gate_status" != "OK" ]; then
+          echo "Quality gate failed: $quality_gate_status"
+          exit 1
+        fi
+    
       
   deploy:
     needs: build
